#if !canImport(ObjectiveC)
import XCTest

extension TestWordSearchBuilder {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TestWordSearchBuilder = [
        ("testBuild_EmptyWordSearch", testBuild_EmptyWordSearch),
        ("testBuild_NameDoesNotExist", testBuild_NameDoesNotExist),
        ("testBuild_SmallWordSearch", testBuild_SmallWordSearch),
    ]
}

extension TestWordSearchSolver {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TestWordSearchSolver = [
        ("testSolve_BackwardDiagonalBackwardFacingWord", testSolve_BackwardDiagonalBackwardFacingWord),
        ("testSolve_BackwardDiagonalForwardFacingWord", testSolve_BackwardDiagonalForwardFacingWord),
        ("testSolve_ForwardDiagonalBackwardFacingWord", testSolve_ForwardDiagonalBackwardFacingWord),
        ("testSolve_ForwardDiagonalForwardFacingWord", testSolve_ForwardDiagonalForwardFacingWord),
        ("testSolve_HorizontalBackwardFacingWord", testSolve_HorizontalBackwardFacingWord),
        ("testSolve_HorizontalForwardFacingWord", testSolve_HorizontalForwardFacingWord),
        ("testSolve_VerticalBackwardFacingWord", testSolve_VerticalBackwardFacingWord),
        ("testSolve_VerticalForwardFacingWord", testSolve_VerticalForwardFacingWord),
        ("testSolveWordSearch", testSolveWordSearch),
        ("testSolveWordSearch_BuildError", testSolveWordSearch_BuildError),
    ]
}

extension TestXYCoordinate {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TestXYCoordinate = [
        ("testPrettyPrint", testPrettyPrint),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(TestWordSearchBuilder.__allTests__TestWordSearchBuilder),
        testCase(TestWordSearchSolver.__allTests__TestWordSearchSolver),
        testCase(TestXYCoordinate.__allTests__TestXYCoordinate),
    ]
}
#endif
